# Generated by Django 4.0.4 on 2022-05-23 21:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default='users/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
